[mysql]
host = "shinkansen.proxy.rlwy.net"     # ✅ Get this from Railway → Public Network
port = 20329                            # ✅ Must match Railway port exactly
user = "root"
password = "cseds@32"       # ✅ Click "Show" to copy it from Railway
database = "railway"
